spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: brgr4684
  sql:
    init:
      mode: always

server:
  port: 8070